/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import Produtos.*;
import java.text.SimpleDateFormat;
/**
 *
 * @author robson
 */
public class TabelaProduto extends javax.swing.JFrame {

    /**
     * Creates new form TabelaProduto
     */
    public TabelaProduto() {
        initComponents();
        preencheTabela();
    }
    
    private void preencheTabela(){
        BdProdutos bdp = new BdProdutos();
        DefaultTableModel modelo = (DefaultTableModel) tProduto.getModel();
        int i = modelo.getRowCount();
        while(i-- >0){
            modelo.removeRow(i);
        }            
        switch ((String)cmbBusca.getSelectedItem()){
            case "Código":
                ArrayList cod = bdp.pesquisaCodigo(Integer.parseInt(tBusca.getText()));
                for(Iterator it = cod.iterator(); it.hasNext();){
                    Produto p = (Produto) it.next();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); 
                    modelo.addRow(new Object[]{p.getCodigo(), p.getEan(), p.getUn(), p.getDescricao(), p.getPrVenda(), p.getPrCusto(), p.getEstmin(), sdf.format(p.getDatacad())});
                }
                break;
            case "Código EAN":
                ArrayList ean = bdp.pesquisaEan(tBusca.getText());
                for(Iterator it = ean.iterator(); it.hasNext();){
                    Produto p = (Produto) it.next();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); 
                    modelo.addRow(new Object[]{p.getCodigo(), p.getEan(), p.getUn(), p.getDescricao(), p.getPrVenda(), p.getPrCusto(), p.getEstmin(), sdf.format(p.getDatacad())});
                }
                break;
            case "Descrição":
                ArrayList desc = bdp.pesquisaDescricao(tBusca.getText());
                for(Iterator it = desc.iterator(); it.hasNext();){
                    Produto p = (Produto) it.next();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); 
                    modelo.addRow(new Object[]{p.getCodigo(), p.getEan(), p.getUn(), p.getDescricao(), p.getPrVenda(), p.getPrCusto(), p.getEstmin(), sdf.format(p.getDatacad())});
                }
                break;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbBusca = new javax.swing.JComboBox();
        tBusca = new javax.swing.JTextField();
        bOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tProduto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca"));

        jLabel1.setText("Buscar");

        cmbBusca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Código EAN", "Descrição" }));
        cmbBusca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBuscaItemStateChanged(evt);
            }
        });

        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bOk)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(cmbBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bOk))
        );

        tProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Código EAN", "Unidade", "Descrição", "Preço de Venda", "Preço de Custo", "Estoque Mínimo", "Data de Cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tProduto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tProduto);
        if (tProduto.getColumnModel().getColumnCount() > 0) {
            tProduto.getColumnModel().getColumn(0).setResizable(false);
            tProduto.getColumnModel().getColumn(0).setPreferredWidth(30);
            tProduto.getColumnModel().getColumn(1).setResizable(false);
            tProduto.getColumnModel().getColumn(1).setPreferredWidth(80);
            tProduto.getColumnModel().getColumn(2).setResizable(false);
            tProduto.getColumnModel().getColumn(2).setPreferredWidth(40);
            tProduto.getColumnModel().getColumn(3).setResizable(false);
            tProduto.getColumnModel().getColumn(3).setPreferredWidth(200);
            tProduto.getColumnModel().getColumn(4).setResizable(false);
            tProduto.getColumnModel().getColumn(4).setPreferredWidth(90);
            tProduto.getColumnModel().getColumn(5).setResizable(false);
            tProduto.getColumnModel().getColumn(5).setPreferredWidth(90);
            tProduto.getColumnModel().getColumn(6).setResizable(false);
            tProduto.getColumnModel().getColumn(6).setPreferredWidth(90);
            tProduto.getColumnModel().getColumn(7).setResizable(false);
            tProduto.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBuscaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBuscaItemStateChanged
       
    }//GEN-LAST:event_cmbBuscaItemStateChanged

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        preencheTabela();
    }//GEN-LAST:event_bOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOk;
    private javax.swing.JComboBox cmbBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tBusca;
    private javax.swing.JTable tProduto;
    // End of variables declaration//GEN-END:variables
}
